language: python
python:
- '3.6'
env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.9.1-linux-amd64.tar.gz
install: echo "Install deps here"
script: echo "Run tests here"
before_deploy:
- mkdir ~/.kube
- echo $CONFIG_PASS | gpg --passphrase-fd 0 kube/kubeconfig.gpg
- cp kube/kubeconfig ~/.kube/config
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
deploy:
  provider: script
  script: helm upgrade forest kube
  on:
    branch: master
