name: forest_develop
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=1.0.4=py36_0
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.3=199
  - jinja2=2.10.1=py36_0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - markupsafe=1.1.1=py36h7b6447c_0
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1b=h7b6447c_1
  - packaging=19.0=py36_0
  - pillow=6.0.0=py36h34e0f95_0
  - pip=19.1.1=py36_0
  - pyparsing=2.4.0=py_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pyyaml=5.1=py36h7b6447c_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py36h7b6447c_0
  - wheel=0.33.2=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/h03/frrn/miniconda3/envs/forest_develop

